version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    ports:
      - :8080
    networks:
      backend:
    depends_on:
      config-server:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  orchestrator:
    build:
      context: .
      dockerfile: ./orchestrator/Dockerfile
    container_name: orchestrator
    ports:
      - :8080
    networks:
      backend:
    depends_on:
      config-server:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - :8080
    networks:
      backend:
    depends_on:
      config-server:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      kafka:
        condition: service_healthy

  uuid-service:
    build:
      context: .
      dockerfile: ./uuid-service/Dockerfile
    container_name: uuid-service
    ports:
      - :8080
    networks:
      backend:
    depends_on:
      config-server:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      kafka:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - 8080:8080
    networks:
      backend:
    depends_on:
      config-server:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
      kafka:
        condition: service_healthy

  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    ports:
      - 8888:8888
    networks:
      backend:
    healthcheck:
      test: "curl -sf http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  discovery-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - :8761
    networks:
      backend:

  postgresdb:
    image: postgres
    restart: always
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
      - ./postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - :5432
    networks:
      backend:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=abracadabra
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9090,EXTERNAL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      backend:
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      backend:

volumes:
  postgresdb-data:
  kafka-data:
  redis-data:

networks:
  backend:






